#version: "3.8"

services:
  mongo-db:
    image: mongo
    container_name: mongo-db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      SPRING_DATA_MONGODB_DATABASE: motivatorDB
      SPRING_DATA_MONGODB_PORT: 27017
    command: ["mongod", "--auth"]
    networks:
      - app-network
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.runCommand('ping')"]
      interval: 30s
      retries: 5

  backend-app:
    image: motivator-backend
    container_name: backend-app
    restart: always
    depends_on:
      - mongo-db
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://admin:admin@mongo-db:27017/motivatorDB?authSource=admin
      SPRING_DATA_MONGODB_DATABASE: motivatorDB
      SPRING_DATA_MONGODB_PORT: 27017
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend-ui:
    image: motivator-frontend
    container_name: frontend-app
    restart: always
    depends_on:
      - backend-app
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
